### ISSUE TITLE
Specify the License

### ISSUE THREAD

**Issue by zalmoxisus** [PaulAvery/mithril-mdl#1]
Great work adopting MDL with Mithril!
It would be really great to add MIT license (or to make it dual licensed) to be intact with Mithril and other libraries.
Thanks again for your work! I've just started to look into it and it's impressive a lot!

**Comment by UhhhWaitWhat** [comment]
I licensed this under BSD-3-Clause.
What benefits would licensing under MIT give me/you? Or better, what problems do you have with the current license?

And I am happy you like the lib :)

**Comment by zalmoxisus** [comment]
For a web app that's ok (as the copyright can be found in the source), but it becomes a bit problematic for a mobile app (as it is in the binary). Of course, it could be done by adding an "about page", just our current structure doesn't involve that. Having MIT or Apache licensed that's not a problem, and I guess for BSD 1-2 as well.

Anyway it was just a suggestion. The library is useful a lot, and so far, testing several components, it seems to be stable.
