### ISSUE TITLE
Not reliable for partial redraws

### ISSUE THREAD

**Issue by reminyborg** [PaulAvery/mithril-mdl#15]
In the readme, problem section:
_Not really reliable for partial redraws (still works, just flickering etc.), due to mdls js adding elements all over the place (or maybe me being an idiot, not sure)_

Is this still a problem?
The components are now upgraded individually and only when they are created in the dom c2d749cb339de0cfa7d54ca9f3e1729d37a0f283.

Can we remove this line? Or is it a problem we still need to solve?

**Comment by UhhhWaitWhat** [comment]
I am actually not quite sure.
The main thing is, material-design-lite inserts a lot of HTML on its own which mithrils virtual dom does not know about. Therefore I am not sure if it redraws reliably. In my tests it seems to work somewhat decently, so I think I will take it out.

Thank You
